package GUI;
public class JFrameSelect extends javax.swing.JFrame 
{
    public JFrameSelect() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_cmsa = new javax.swing.JButton();
        btn_phsa = new javax.swing.JButton();
        btn_mtma = new javax.swing.JButton();
        btn_stsa = new javax.swing.JButton();
        btn_chem = new javax.swing.JButton();
        btn_ecoa = new javax.swing.JButton();
        btn_mcba = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Select Semester");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Select any one of the following departments");

        btn_cmsa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cmsa.setText("CMSA");
        btn_cmsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cmsaActionPerformed(evt);
            }
        });

        btn_phsa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_phsa.setText("PHSA");
        btn_phsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phsaActionPerformed(evt);
            }
        });

        btn_mtma.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_mtma.setText("MTMA");
        btn_mtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mtmaActionPerformed(evt);
            }
        });

        btn_stsa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_stsa.setText("STSA");
        btn_stsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stsaActionPerformed(evt);
            }
        });

        btn_chem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_chem.setText("CEMA");
        btn_chem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chemActionPerformed(evt);
            }
        });

        btn_ecoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_ecoa.setText("ECOA");
        btn_ecoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecoaActionPerformed(evt);
            }
        });

        btn_mcba.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_mcba.setText("MCBA");
        btn_mcba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mcbaActionPerformed(evt);
            }
        });

        jButton_back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_mtma)
                                .addGap(18, 18, 18)
                                .addComponent(btn_phsa)
                                .addGap(18, 18, 18)
                                .addComponent(btn_chem)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cmsa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btn_mcba)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ecoa)
                                .addGap(26, 26, 26)
                                .addComponent(btn_stsa)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mtma)
                    .addComponent(btn_phsa)
                    .addComponent(btn_chem)
                    .addComponent(btn_cmsa))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mcba)
                    .addComponent(btn_ecoa)
                    .addComponent(btn_stsa))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void display(String d)
    {
        int sem=Integer.parseInt(""+jComboBox1.getSelectedItem());
        JFrameDept ob=new JFrameDept(d,sem);
        ob.setSize(800,500);
        ob.setVisible(true);
    }
    private void btn_cmsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cmsaActionPerformed
        String d=evt.getActionCommand();
        display(d);
        
    }//GEN-LAST:event_btn_cmsaActionPerformed

    private void btn_phsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phsaActionPerformed
        String d=evt.getActionCommand();
        display(d);
        
    }//GEN-LAST:event_btn_phsaActionPerformed

    private void btn_mtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mtmaActionPerformed
        String d=evt.getActionCommand();
        display(d);
    }//GEN-LAST:event_btn_mtmaActionPerformed

    private void btn_stsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stsaActionPerformed
        String d=evt.getActionCommand();
        display(d);
    }//GEN-LAST:event_btn_stsaActionPerformed

    private void btn_chemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chemActionPerformed
        String d=evt.getActionCommand();
        display(d);
    }//GEN-LAST:event_btn_chemActionPerformed

    private void btn_ecoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecoaActionPerformed
        String d=evt.getActionCommand();
        display(d);
    }//GEN-LAST:event_btn_ecoaActionPerformed

    private void btn_mcbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mcbaActionPerformed
        String d=evt.getActionCommand();
        display(d);
    }//GEN-LAST:event_btn_mcbaActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chem;
    private javax.swing.JButton btn_cmsa;
    private javax.swing.JButton btn_ecoa;
    private javax.swing.JButton btn_mcba;
    private javax.swing.JButton btn_mtma;
    private javax.swing.JButton btn_phsa;
    private javax.swing.JButton btn_stsa;
    private javax.swing.JButton jButton_back;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
